name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:          # Allows manual trigger

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake SVG
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Kcbir
          outputs: dist/github-contribution-grid-snake.svg

      # Deploy the dist folder to the output branch
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: ./dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
